"""relationship added

Revision ID: 7a521ed2160d
Revises: 5448179eb27d
Create Date: 2021-09-06 21:21:23.885161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a521ed2160d'
down_revision = '5448179eb27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
