"""2nd migration

Revision ID: fcfea0c840c5
Revises: 66d3814ff5fb
Create Date: 2021-09-05 14:30:15.769030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfea0c840c5'
down_revision = '66d3814ff5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('is_correct', sa.Boolean(), nullable=False))
    op.add_column('answers', sa.Column('question_id', sa.Integer(), nullable=True))
    op.alter_column('answers', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'answers', ['title'])
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    op.add_column('questions', sa.Column('theme_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'questions', ['title'])
    op.create_foreign_key(None, 'questions', 'themes', ['theme_id'], ['id'])
    op.alter_column('themes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'themes', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='unique')
    op.alter_column('themes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_column('questions', 'theme_id')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='unique')
    op.alter_column('answers', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('answers', 'question_id')
    op.drop_column('answers', 'is_correct')
    # ### end Alembic commands ###
